# Generated by Django 4.2.2 on 2023-12-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(max_length=5),
        ),
    ]
